### ISSUE TITLE
Epic: Redesign and decoupling front-end

### ISSUE THREAD

**Issue by losolio** [losol/eventuras#511]
The new front-end will need to be feature complete for participants before release. For administrator all new functionality will be implemented in the Next front-end, but the two UIs will live in parallell for some time before the Eventuras.Web project will be retired. 

Participants UI

- [x] User login with Auth0
- [ ] Registration to events and customize products ordered
- [ ] Profile page
- [ ] See own event registrations

Administrator front-end

- [x] Email all participants UI
- [ ] SMS all participants UI
- [ ] Product list page
- [ ] Edit event details
- [ ] See all orders for event
- [ ] Invoice functionality
